version: "3.9"

networks:
  private:

services:
  bot:
    image: ghcr.io/artrey/rielgobot-pro:latest
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./allowedLocation.geojson:/var/data/allowedLocation.geojson
      - ./localStorageSetup.js:/var/data/localStorageSetup.js
    networks:
      - private
