[tool.black]
line-length = 120
exclude = '''
/(
  # Copied from: https://github.com/psf/black/blob/master/pyproject.toml
  | \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | venv
  | _build
  | build
  | dist

  # Specific to the project
  | migrations
  | static
  | media
)/
'''

[tool.flake8]
# Base flake8 configuration:
# https://flake8.pycqa.org/en/latest/user/configuration.html
show-source = true
statistics = false
doctests = true

# darglint configuration:
# https://github.com/terrencepreilly/darglint
strictness = 'long'
docstring-style = 'numpy'

# Plugins:
max-complexity = 8
max-line-length = 120
max-methods = 9

# Disable some pydocstyle checks:
# Exclude some pydoctest checks globally:
ignore = 'W503'

# Due to this, Flake8 will raise E203 whitespace before ':' warnings.
# Since this warning is not PEP 8 compliant, Flake8 should be configured to ignore it
extend-ignore = 'E203'

# Excluding some directories:
exclude = [
  '.git',
  '__pycache__',
  '.venv',
  'venv',
  '.eggs',
  '*.egg',
  'manage.py',
  '*/settings.py',
  '*/migrations',
]

# Ignoring some errors in some files:
per-file-ignores = [
  # Enable `assert` keyword and magic numbers for tests:
  'tests/*.py: S101, WPS114, WPS226, WPS432',
  # Allow string constant over-use in admin:
  'admin.py: WPS226',
  # Allow magic number in models:
  'models.py: WPS432',
]

[tool.isort]
profile = 'black'
include_trailing_comma = true
use_parentheses = true
# See https://github.com/timothycrosley/isort#multi-line-output-modes
multi_line_output = 3
line_length = 120
skip_glob = '*/migrations'

[tool.pytest.ini_options]
# Directories that are not visited by pytest collector:
norecursedirs = [
  '.venv',
  'venv',
  'hooks',
  '*.egg',
  '.eggs',
  'dist',
  'build',
  'docs',
  '.tox',
  '.git',
  '__pycache__',
]

# Extra options:
addopts = [
  '--strict-markers',
  '--tb=short',
  '--doctest-modules',
]

testpaths = 'tests/'

python_files = 'test_*.py'

filterwarnings = [
  'error',
  'ignore::ImportWarning:importlib',
  'ignore::DeprecationWarning',
  'ignore::PendingDeprecationWarning:django',
]

env = [
  'DEBUG=False',
]

[tool.coverage.run]
omit = [
  '*/migrations/*',
  '*/management/*',
]
